org: agora
app: agora
service:
  name: agora-payment-service
  description: Zenius Core Payment Membership Service

custom:
  membership_db_local:
    {
      'host': 'unused',
      'username': 'unused',
      'password': 'unused',
      'port': 0000,
    }
  membership_db_dev: ${ssm:/aws/reference/secretsmanager/MEMBERSHIP_DB_DEV~true}
  membership_db_staging: {}
  membership_db_prod: {}

  customDomain:
    domainName: payment.${self:provider.stage}.zeniusnet.com
    stage: ${self:provider.stage}
    certificateName: '*.dev.zeniusnet.com'
    createRoute53Record: true
    endpointType: 'regional'

provider:
  name: aws
  role: arn:aws:iam::210491301395:role/lambda-role
  runtime: nodejs10.x
  region: 'ap-southeast-1'
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: '*'
  environment:
    STAGE: ${self:provider.stage}
    DB_HOST: ${self:custom.membership_db_${self:provider.stage}.host}
    DB_USERNAME: ${self:custom.membership_db_${self:provider.stage}.username}
    DB_PASSWORD: ${self:custom.membership_db_${self:provider.stage}.password}
    DB_PORT: ${self:custom.membership_db_${self:provider.stage}.port}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-domain-manager

package:
  exclude:
    - .git/**
    - dist/**
    - test/**
    - e2e/**
    - views/**
    - docker-postgres-init/**
    - coverage/**
    - nodemon.json
    - README.md
    - ./*.json
    - ./*.log
    - ./*.yml
    - ./*.lock
    - node_modules/babel-**/**
    - node_modules/@babel/**
    - node_modules/browserify**/**
    - node_modules/figlet/**
    - node_modules/@type/**
    - node_modules/aws-sdk/**



functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          cors: true
          method: any
          path: '{proxy+}'
      - http:
          cors: true
          method: get
          path: 'swagger'
      - http:
          cors: true
          method: any
          path: 'api/payment'
      - http:
          cors: true
          method: any
          path: 'paymentZenpres'
