org: agora
app: agora
service:
  name: otp-service
  description: Otp Service

provider:
  name: aws
  description: Otp Service
  role: arn:aws:iam::210491301395:role/lambda-role
  runtime: nodejs10.x
  region: 'ap-southeast-1'
  memorySize: 512
  timeout: 10s
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'secretsmanager:GetSecretValue'
      Resource: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

package:
  exclude:
    - .git/**
    - dist/**
    - test/**
    - e2e/**
    - views/**
    - keycloak-presets/**
    - docker-postgres-init/**
    - coverage/**
    - nodemon.json
    - README.md
    - ./*.json
    - ./*.log
    - ./*.yml
    - ./*.lock
    - node_modules/babel-**/**
    - node_modules/@babel/**
    - node_modules/browserify**/**
    - node_modules/figlet/**
    - node_modules/@type/**
    - node_modules/aws-sdk/**
  include:
    - node_modules/mysql*/**


functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          path: /swagger
          method: GET
          cors: true
      - http:
          cors: true
          method: any
          path: '{proxy+}'
