org: agora
app: agora
service:
  name: agora-auth-service

custom:
  dev:
    domain: 'auth.dev.api-agora.com'
    certificate: '*.api-agora.com'
    keycloak_config: ${ssm:/aws/reference/secretsmanager/Accounts/Keycloak/dev~true}
    saas_keycloak_config: ${ssm:/aws/reference/secretsmanager/Accounts/Keycloak/dev~true}
  staging:
    domain: 'auth.staging.api-agora.com'
    certificate: '*.api-agora.com'
    keycloak_config: ${ssm:/aws/reference/secretsmanager/Accounts/Keycloak/staging~true}
    saas_keycloak_config: ${ssm:/aws/reference/secretsmanager/Accounts/Keycloak/staging~true}
  prod:
    domain: 'auth.api-agora.com'
    certificate: '*.api-agora.com'
    keycloak_config: null
    saas_keycloak_config: null

  # Custom Domain
  customDomain:
    domainName: ${self:custom.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
    certificateName: ${self:custom.${self:provider.stage}.certificate}
    createRoute53Record: true
    endpointType: 'regional'

provider:
  name: aws
  description: Agora Auth Service
  role: arn:aws:iam::207219370128:role/lambda-role
  runtime: nodejs10.x
  region: 'ap-southeast-1'
  memorySize: 512
  timeout: 10s
  stage: ${opt:stage, 'dev'}
  deploymentBucket: agora-serverless
  environment:
    STAGE: ${self:provider.stage}
    KEYCLOAK_BASE_URL: ${self:custom.${self:provider.stage}.keycloak_config.KEYCLOAK_BASE_URL}
    SAAS_KEYCLOAK_BASE_URL: ${self:custom.${self:provider.stage}.saas_keycloak_config.KEYCLOAK_BASE_URL}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-domain-manager
  - serverless-pseudo-parameters

package:
  exclude:
    - .git/**
    - dist/**
    - test/**
    - e2e/**
    - views/**
    - keycloak-presets/**
    - docker-postgres-init/**
    - coverage/**
    - nodemon.json
    - README.md
    - ./*.json
    - ./*.log
    - ./*.yml
    - ./*.lock
    - node_modules/babel-**/**
    - node_modules/@babel/**
    - node_modules/browserify**/**
    - node_modules/figlet/**
    - node_modules/@type/**
    - node_modules/@types/**
    - node_modules/aws-sdk/**
  include:
    - node_modules/mysql*/**
    - package.json

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          method: get
          path: /swagger
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /login
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /logout
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /sessions
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /verifyToken
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /verifyToken/{realm}
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
      - http:
          method: any
          path: /refreshToken
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Realm
            allowCredentials: true
