version: "2"
services:
  postgres:
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ae_learning_new
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
