org: agora
app: agora
service:
  name: agora-keycloak-config-service

custom:
  # Keycloak Config
  keycloak_config_local: {"KEYCLOAK_BASE_URL": null}
  keycloak_config_dev: ${ssm:/aws/reference/secretsmanager/agora/keycloak_config/dev~true}
  keycloak_config_staging: {}
  keycloak_config_prod: {}

  # DB Config
  agora_db_local: {"host": "unused","username": "unused","password": "unused","port": 0000}
  agora_db_dev: ${ssm:/aws/reference/secretsmanager/AGORA_DB_DEV~true}
  agora_db_staging:  ${ssm:/aws/reference/secretsmanager/AGORA_DB_STAGING~true}
  agora_db_prod: {}

  stages: {
    dev: {domain: "keycloak-config.api-dev.agora.id", certificate: "*.api-dev.agora.id"},
    staging: {domain: "keycloak-config.api-staging.agora.id", certificate: "*.api-staging.agora.id"},
    prod: {domain: "", certificate: ''},
  }

  # Custom Domain
  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
    certificateName: ${self:custom.stages.${self:provider.stage}.certificate}
    createRoute53Record: true
    endpointType: 'regional'

  # SNS
  accountCreateTopic: agora-account-create-${self:provider.stage}

provider:
  name: aws
  description: Agora Keycloak Service
  role: arn:aws:iam::210491301395:role/lambda-role
  runtime: nodejs10.x
  region: 'ap-southeast-1'
  memorySize: 512
  timeout: 10s
  stage: ${opt:stage, 'dev'}
  deploymentBucket: ${self:provider.region}.serverlessdeploys
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
          - secretsmanager:GetSecretValue
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}
    KEYCLOAK_MAIN_AUTH_URL: ${self:custom.keycloak_config_${self:provider.stage}.KEYCLOAK_MAIN_AUTH_URL}
    # DB Config
    DB_NAME: keycloak_service
    DB_HOST: ${self:custom.agora_db_${self:provider.stage}.host}
    DB_USERNAME: ${self:custom.agora_db_${self:provider.stage}.username}
    DB_PASSWORD: ${self:custom.agora_db_${self:provider.stage}.password}
    DB_PORT: ${self:custom.agora_db_${self:provider.stage}.port}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-domain-manager
  - serverless-pseudo-parameters

package:
  exclude:
    - .git/**
    - dist/**
    - test/**
    - e2e/**
    - views/**
    - keycloak-presets/**
    - docker-postgres-init/**
    - coverage/**
    - nodemon.json
    - README.md
    - ./*.json
    - ./*.log
    - ./*.yml
    - ./*.lock
    - node_modules/babel-**/**
    - node_modules/@babel/**
    - node_modules/browserify**/**
    - node_modules/figlet/**
    - node_modules/@type/**
    - node_modules/@types/**
    - node_modules/aws-sdk/**
  include:
    - node_modules/mysql*/**
    - package.json


functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
      - http:
          method: get
          path: /swagger
          cors: true
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /realm/{param}
          cors: true

